### PR TITLE
Add method to set state of CheckButtons.

### PR DESCRIPTION
**Pull request by H-M-H**

### CODE REVIEW

**Comment by H-M-H** [comment]
I kind of need this for one of my projects and think it is somewhat essential to be able to set the default state.

Apart from that thanks for providing these bindings :)

**Comment by MoAlyousef** [comment]
Hi,

Thanks for the pull request.

**Comment by H-M-H** [comment]
That was fast, thank you!

**Comment by MoAlyousef** [comment]
No problem. 
I have published a minor version 0.3.9 with the relevant changes, similarly for RoundButton, RadioButton, LightButton and ToggleButton. These can be accessed by their respective methods, or via the ButtonExt trait methods using set() and is_set().

**Pull request merged**
